apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nasir-nginx-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-0734ed2d81043d90c"
  subnets:
    private:
      ap-southeast-1a:
          id: "subnet-0a81ab3974f428260"
      ap-southeast-1b:
          id: "subnet-0f62bde5cde2fbc99"
    public:
      ap-southeast-1a:
          id: "subnet-0eed122751ceb5d7a"
      ap-southeast-1b:
          id: "subnet-02c11d6933657211c"

nodeGroups:
  - name: ng
